export const ActionTypes = {
  //loadingAction
  LOADING: "LOADING",

  //authActionTypes
  LOGIN: "LOGIN",
  FETCH_CURRENTUSER: "FETCH_CURRENTUSER",
  LOGOUT: "LOGOUT",

  // profileActionTypes
  FETCH_PROFILE: "FETCH_PROFILE",
  EDIT_PROFILE: "EDIT_PROFILE",

  //userActionTypes
  FETCH_USERLIST: "FETCH_USERLIST",
  EDIT_USER: "EDIT_USER",

  FETCH_SALON: "FETCH_SALON",

  // category
  EDIT_CATEGORY: "EDIT_CATEGORY",
  FETCH_CATEGORY: "FETCH_CATEGORY",

  // subcategory
  FETCH_SUBCATEGORY: "FETCH_SUBCATEGORY",
  EDIT_SUBCATEGORY: "EDIT_SUBCATEGORY",

  // styles
  FETCH_STYLES: "FETCH_STYLES",

  // banner
  FETCH_BANNER: "FETCH_BANNER",
};
